//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCV_CSE.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_Municipio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_Municipio()
        {
            this.CentrosVotacion = new HashSet<CentrosVotacion>();
        }
    
        public int id_CatMunicipio { get; set; }
        public string nomMunicipio { get; set; }
        public string descripcion { get; set; }
        public int id_CatDepartamento { get; set; }
        public string imgPlano { get; set; }
        public string imdMapa { get; set; }
    
        public virtual cat_Departamento cat_Departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CentrosVotacion> CentrosVotacion { get; set; }
    }
}
