//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCV_CSE.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentrosVotacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CentrosVotacion()
        {
            this.GaleriaCentroVotacion = new HashSet<GaleriaCentroVotacion>();
        }
    
        public int id_CentroVotacion { get; set; }
        public string nomCenVotacion { get; set; }
        public string direccionCenVotacion { get; set; }
        public string ubicacionCenVotacion { get; set; }
        public string derroteroCenVotacion { get; set; }
        public string circunscripcionCenVotacion { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> idTipoCV { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public string fotoFachada { get; set; }
        public string Estado { get; set; }
        public bool Activo { get; set; }
        public int id_CatMunicipio { get; set; }
        public string imgPlano { get; set; }
    
        public virtual cat_Municipio cat_Municipio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GaleriaCentroVotacion> GaleriaCentroVotacion { get; set; }
    }
}
