//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCV_CSE.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GaleriaCentroVotacion
    {
        public System.Guid idGaleriaCentro { get; set; }
        public string fotoUrl { get; set; }
        public System.DateTime fechaHoraCreacion { get; set; }
        public Nullable<int> id_CentroVotacion { get; set; }
    
        public virtual CentrosVotacion CentrosVotacion { get; set; }
    }
}
