//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCV_CSE.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class JRV
    {
        public int id_JRV { get; set; }
        public string codeJRV { get; set; }
        public Nullable<int> cantInscritos { get; set; }
        public Nullable<int> cantVerificados { get; set; }
        public Nullable<int> id_CentroVotacion { get; set; }
    }
}
