//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCV_CSE.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class JRV
    {
        public int id_JRV { get; set; }
        public string codeJRV { get; set; }
        public Nullable<int> cantInscritos { get; set; }
        public Nullable<int> cantVerificados { get; set; }
        public Nullable<int> id_CentroVotacion { get; set; }
    
        public virtual CentrosVotacion CentrosVotacion { get; set; }
    }
}
