//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCV_CSE.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBJUNTASEntities : DbContext
    {
        public DBJUNTASEntities()
            : base("name=DBJUNTASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cat_Departamento> cat_Departamento { get; set; }
        public virtual DbSet<cat_Municipio> cat_Municipio { get; set; }
        public virtual DbSet<cat_TipoCV> cat_TipoCV { get; set; }
        public virtual DbSet<CentrosVotacion> CentrosVotacion { get; set; }
        public virtual DbSet<GaleriaCentroVotacion> GaleriaCentroVotacion { get; set; }
        public virtual DbSet<JRV> JRV { get; set; }
        public virtual DbSet<vwPADRON> vwPADRON { get; set; }
    
        public virtual ObjectResult<TotalConsolidado_Result> TotalConsolidado(Nullable<int> iddpto)
        {
            var iddptoParameter = iddpto.HasValue ?
                new ObjectParameter("iddpto", iddpto) :
                new ObjectParameter("iddpto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TotalConsolidado_Result>("TotalConsolidado", iddptoParameter);
        }
    }
}
