//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCV_CSE.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PADRON
    {
        public Nullable<int> id { get; set; }
        public string tipo_id { get; set; }
        public Nullable<int> expediente { get; set; }
        public string ci { get; set; }
        public string cod_munic { get; set; }
        public Nullable<int> jrv { get; set; }
        public string papell { get; set; }
        public string sappell { get; set; }
        public string pnom { get; set; }
        public string snom { get; set; }
        public string lugar_nac { get; set; }
        public Nullable<System.DateTime> fecha_nac { get; set; }
        public string sexo { get; set; }
        public string domicilio { get; set; }
        public Nullable<System.DateTime> f_solicitud { get; set; }
        public Nullable<System.DateTime> f_expedi { get; set; }
        public Nullable<System.DateTime> f_inclus { get; set; }
    }
}
